# Fly.io configuration for Sui/Walrus Chatbot API

# IMPORTANT: Replace with your unique Fly app name OR pass -a <name> on CLI
app = "walrus chatbot"

# Optionally set your closest region code (e.g., lhr, iad, fra, sin)
# primary_region = "REPLACE_WITH_REGION_CODE"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1
  processes = ["app"]

# Recommended small VM size (can also set via CLI)
# [vm]
#   size = "shared-cpu-1x"
#   memory_mb = 256


